CREATE DATABASE IF NOT EXISTS wishes DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

CREATE USER 'dbuser'@'localhost' IDENTIFIED BY '12345678';
CREATE USER 'dbuser'@'%' IDENTIFIED BY '12345678';

GRANT ALL ON wishes.* TO 'dbuser'@'localhost';
GRANT ALL ON wishes.* TO 'dbuser'@'%';
FLUSH PRIVILEGES;